name: 'go-gin'
port: 8080
logsLocation: './logs'

mysql:
    host: 'localhost'
    port: 3306
    username: 'root'
    password: '123456'
    dbName: 'student'

regis:
    host: 'localhost'
    port: 6379
